development:
  adapter: postgresql
  encoding: unicode
  database: photo_development
  pool: 5
  username: 
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: photo_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: photo_production
  pool: 5
  username: 
  password:
